spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tovar_hisob_kitobi
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
link: localhost:${server.port}
